pipeline {
  agent any
  options {
    skipStagesAfterUnstable()
  }
  environment {
    IMAGE_BASE = 'simple-example'
    IMAGE_TAG = "v$BUILD_NUMBER"
    IMAGE_NAME = "${env.IMAGE_BASE}:${env.IMAGE_TAG}"
    IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
    DOCKERFILE_NAME = "Dockerfile"
	APP_DIR = 'simple-example'

  }
  
	tools {
			maven 'maven382'
	}
  stages {
    stage("Prepare container") {

      stages {
	  
	  	stage ('Initialize') {
			steps {
				sh '''
					echo "PATH = ${PATH}"
					echo "M2_HOME = ${M2_HOME}"
				'''
			}
		}
	  
        stage('Build') {
          steps {
            sh "mvn -f ${APP_DIR}/pom.xml clean install"
          }
        }

		stage('Push images') {
		  steps {

			
			
			
			 steps {
                sh '''
                    cd ${APP_DIR}
                    docker image build -t ${env.IMAGE_NAME} .
                    docker login -u ${cd_registry_cred_USR} -p ${cd_registry_cred_PSW} ${cd_registry_url}
                    docker tag ${env.IMAGE_NAME} ${cd_registry_url}/${env.IMAGE_NAME}
                    docker push ${cd_registry_url}/${env.IMAGE_NAME}
                '''
            }
            post {
                always {
                    sh '''
                        docker logout ${cd_registry_url}
                        '''
                    }
                }
			
			
			
			
			
			
			
		  }
		}



      }
    }


  }
}
