pipeline {
  agent any
  options {
    skipStagesAfterUnstable()
  }
  environment {
    IMAGE_BASE = 'simple-example'
    IMAGE_TAG = "v$BUILD_NUMBER"
    IMAGE_NAME = "${env.IMAGE_BASE}:${env.IMAGE_TAG}"
    IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
    DOCKERFILE_NAME = "simple-example/Dockerfile"
	APP_DIR = 'simple-example'

  }
  
	tools {
			maven 'maven382'
	}
  stages {
    stage("Prepare container") {

      stages {
	  
	  	stage ('Initialize') {
			steps {
				sh '''
					echo "PATH = ${PATH}"
					echo "M2_HOME = ${M2_HOME}"
				'''
			}
		}
	  
        stage('Build') {
          steps {
            sh "mvn -f ${APP_DIR}/pom.xml clean install"
          }
        }

		stage('Push images') {
		  steps {
			script {
			  cd ${APP_DIR}
			  def dockerImage = docker.build("${env.IMAGE_NAME}", "-f ${env.DOCKERFILE_NAME} .")
			  docker.withRegistry('localhost:5000', 'docker_registry_local') {
				dockerImage.push()
				dockerImage.push("latest")
			  }
			  echo "Pushed Docker Image: ${env.IMAGE_NAME}"
			}
			sh "docker rmi ${env.IMAGE_NAME} ${env.IMAGE_NAME_LATEST}"
		  }
		}



      }
    }


  }
}
