pipeline {
  agent any
  options {
    skipStagesAfterUnstable()
  }
  environment {
    IMAGE_BASE = 'simple-example'
    IMAGE_TAG = "v77"
    IMAGE_NAME = "${env.IMAGE_BASE}:${env.IMAGE_TAG}"
    IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
    DOCKERFILE_NAME = "Dockerfile"
	APP_DIR = 'simple-example'

  }
  
	tools {
			maven 'maven382'
	}
  stages {
    stage("Prepare container") {

      stages {
	  
	  	stage ('Initialize') {
			steps {
				sh '''
					echo "PATH = ${PATH}"
					echo "M2_HOME = ${M2_HOME}"
				'''
			}
		}
	  
        stage('Build') {
          steps {
            sh "mvn -f ${APP_DIR}/pom.xml clean install"
          }
        }

		stage('Push images') {


			steps {
                sh '''
                    cd simple-example
					docker image build -t simple-example:v001 .
                    docker login -u admin -p admin http://localhost:5000
                    docker tag simple-example:v001 http://192.168.1.3:5000/simple-example:v001
                    docker push http://192.168.1.3:5000/simple-example:v001
                '''
            }
            post {
                always {
                    sh '''
                        docker logout ${cd_registry_url}
                        '''
                    }
            }

		}



      }
    }


  }
}
